name: Build Docker image

on:
  push:
    branches:
      - "font-cn"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t excalidraw .
