name: Publish Docker

on:
  push:
    branches:
      - "font-cn"

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    environment: docker # 这里指定了要使用的环境名称
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/excalidraw:latest
